# This workflow will install Python dependencies, run tests and lint with a variety of Python versions

name: Tests

on:
  pull_request:
    branches:
      - main

env:
  UV_SYSTEM_PYTHON: 1

jobs:

  coverage:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Setup uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.5.18"

    - name: Install all dependencies
      run: uv sync --extra progress

    - name: Run Coverage
      run: make coverage

    - name: Upload test results to Codecov
      uses: codecov/test-results-action@v1
      with:
        file: ./junit.xml
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true

    - name: Test publish to PyPI
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
        UV_PUBLISH_URL: "https://test.pypi.org/legacy/"
      run: |
        uv build
        uv publish

  python-checks:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.5.18"
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: uv sync

    - name: Static tests
      run: make static-tests

    - name: Unit tests with minimal dependencies
      run: make unit-tests

    - name: Unit tests with extra dependencies
      run: |
        uv sync --extra progress
        make unit-tests
