# This workflow will install Python dependencies, run tests and lint with a variety of Python versions

name: Tests

on:
  pull_request:
    branches:
      - main

jobs:

  coverage:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'

    - name: Install Poetry
      run: pip install poetry==1.5.1

    - name: Install all dependencies
      run: poetry install -E progress

    - name: Run Coverage
      run: make coverage

    - name: Upload Coverage
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
        fail_ci_if_error: true

  python-checks:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: pip install poetry==1.5.1

    - name: Install dependencies
      run: poetry install

    - name: Static tests
      run: make static-tests

    - name: Unit tests with minimal dependencies
      run: make unit-tests

    - name: Unit tests with extra dependencies
      run: |
        poetry install -E progress
        make unit-tests
